### ISSUE TITLE
Take Flavio dG/dq2 distribution instead of implementing our own (check if we can also use other distributions)

### ISSUE THREAD

**Issue by klieret** [clusterking/clusterking#13]
perhaps also in the variable ``w`` which most experimentalists use

**Comment by jasonaebischerGIT** [comment]
The problem is, that in flavio this particular observable is not implemented (see [observables](https://flav-io.github.io/docs/obs/bhadrondecays-semileptonictreeleveldecays.html)) since dG/dq2 is the differential 3-fold 5-body differential decay rate which is quite a complicated expression given in eq. (51) of [1602.07671](https://arxiv.org/abs/1602.07671).
Actually I checked the whole implementation back then done by Alejandro, and we both implemented the of (A5)-(A13) individually and got the same results.

**Comment by jasonaebischerGIT** [comment]
Since

<a href="https://www.codecogs.com/eqnedit.php?latex=w=\frac{m_B^2+m_D^2-q^2}{2m_B m_D}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?w=\frac{m_B^2+m_D^2-q^2}{2m_Bm_D}," title="E=mc^2" /></a>



one has in the notation of [1602.07671](https://arxiv.org/abs/1602.07671)

<a href="https://www.codecogs.com/eqnedit.php?latex=w=\frac{m_B^2+m_D^2-q^2}{2m_B m_D}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{d\Gamma_5}{dw}=-2m_Bm_D\frac{d\Gamma_5}{dq^2}" title="E=mc^2" /></a>

**Comment by klieret** [comment]
I'm gonna close this, implementing w will be easy.
